# Generated by Django 6.1 on 2026-08-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastapiconnection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lungsimageprediction',
            name='gradcam_image',
            field=models.CharField(blank=True, max_length=255555555, null=True),
        ),
    ]
