# Generated by Django 6.1 on 2026-08-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventoryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
