# Generated by Django 6.1 on 2026-08-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='is_active',
        ),
    ]
