# Generated by Django 6.1 on 2026-08-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_hospital_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='hospital_email',
            new_name='hospital',
        ),
    ]
