# Generated by Django 6.1 on 2026-08-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_hospital_email_patient_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
