# Generated by Django 6.1 on 2026-08-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient__status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='_status',
            new_name='status',
        ),
    ]
