# Generated by Django 6.1 on 2026-08-22 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('specialization', models.CharField(choices=[('GENERAL', 'General Physician'), ('CARDIOLOGIST', 'Cardiologist'), ('NEUROLOGIST', 'Neurologist'), ('DERMATOLOGIST', 'Dermatologist'), ('ONCOLOGIST', 'Oncologist'), ('ORTHOPEDIC', 'Orthopedic'), ('PEDIATRICIAN', 'Pediatrician'), ('PSYCHIATRIST', 'Psychiatrist'), ('RADIOLOGIST', 'Radiologist'), ('PULMONOLOGIST', 'Pulmonologist'), ('OTHER', 'Other')], max_length=50)),
                ('department', models.CharField(choices=[('GENERAL_MEDICINE', 'General Medicine'), ('CARDIOLOGY', 'Cardiology'), ('NEUROLOGY', 'Neurology'), ('DERMATOLOGY', 'Dermatology'), ('ONCOLOGY', 'Oncology'), ('ORTHOPEDICS', 'Orthopedics'), ('PEDIATRICS', 'Pediatrics'), ('PSYCHIATRY', 'Psychiatry'), ('RADIOLOGY', 'Radiology'), ('PULMONOLOGY', 'Pulmonology'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('available_days', models.CharField(blank=True, max_length=255)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_to', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
