# Generated by Django 6.1 on 2026-08-22 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('specialization', models.CharField(choices=[('GENERAL', 'General Physician'), ('CARDIOLOGIST', 'Cardiologist'), ('NEUROLOGIST', 'Neurologist'), ('DERMATOLOGIST', 'Dermatologist'), ('ONCOLOGIST', 'Oncologist'), ('ORTHOPEDIC', 'Orthopedic'), ('PEDIATRICIAN', 'Pediatrician'), ('PSYCHIATRIST', 'Psychiatrist'), ('RADIOLOGIST', 'Radiologist'), ('PULMONOLOGIST', 'Pulmonologist'), ('OTHER', 'Other')], max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('medical_license_number', models.CharField(max_length=100, unique=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('hospital_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
